# Shows the "Sponsor" button on the repository.
# https://docs.github.com/sponsors/receiving-sponsorships-through-github-sponsors/configuring-github-sponsors-in-your-repository
buy_me_a_coffee: christianlugerat
