import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFileSync } from 'node:fs';

// Stamp the version into the banner so main.js has unique bytes for every
// release, even when the source didn't change between two versions. This keeps a
// new release from inheriting an older release's build-provenance attestation,
// which is keyed by file digest and cannot be deleted. See version-bump.mjs.
const version = JSON.parse(readFileSync('manifest.json', 'utf8')).version;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Focus First v${version}
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
